global:
  image:
    pullPolicy: Always
  volumes:
    keep: false
  storageClassName: nfs-provisioner
es:
  replicaCount: 
    master: 1
    data: 1
    coordinator: 1
  heapSize:
    master: 128m
    data: 512m
    coordinator: 128m
  image:
    repository: elastic/elasticsearch
    tag: 6.2.4
  service:
    master:
      name: es-discovery
      type: ClusterIP
      externalTransportPort: 9300
      internalTransportPort: 9300
    data:
      name: es-data
      type: ClusterIP
      externalTransportPort: 9300
      internalTransportPort: 9300
    coordinator:
      name: es-coordinator
      type: ClusterIP
      externalApiPort: 9200
      internalApiPort: 9200
      externalTransportPort: 9300
      internalTransportPort: 9300
      nodePort: 30011
  volumes:
    master:
      storageClassName: nfs-provisioner
      accessModes: ReadWriteOnce
      size: 8Gi
      mountPath: /export
    data:
      storageClassName: nfs-provisioner
      accessModes: ReadWriteOnce
      size: 8Gi
      mountPath: /export
  cluster:
    name: elk
    env:
      # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
      # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
      # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
      MINIMUM_MASTER_NODES: "1"
filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 6.2.4
logstash:
  enabled: true
  replicaCount: 1
  image:
    repository: elastic/logstash
    tag: 6.2.4
  service:
    name: logstash
    type: ClusterIP
    externalPort: 5044
    internalPort: 5044
kibana:
  replicaCount: 1
  image:
    repository: elastic/kibana
    tag: 6.2.4
  service:
    name: kibana
    type: NodePort
    externalPort: 5601
    internalPort: 5601
    nodePort: 30061
selectPort: true
